### ISSUE TITLE
Syntax errors don't print the name of the file

### ISSUE THREAD

**Issue by thatch** [omnilib/ufmt#89]
If there's a file containing a an unclosed paren, e.g. just `(` ithen `python -m ufmt check pkg` prints a bunch of stuff but not the name of the file:

```
(.venv) [tim@aerynsun wreck]$ make lint
python -m ufmt check wreck setup.py
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/libcst/_parser/base_parser.py", line 151, in _add_token
    plan = stack[-1].dfa.transitions[transition]
KeyError: TokenType(ENDMARKER)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 202, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 202, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/ufmt/core.py", line 88, in ufmt_file
    dst_contents = ufmt_string(path, src_contents, usort_config, black_config)
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/ufmt/core.py", line 43, in ufmt_string
    content = usort_string(content, usort_config, path)
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/usort/api.py", line 90, in usort_string
    raise result.error
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/usort/api.py", line 31, in usort
    module = try_parse(data=data, path=path)
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/usort/util.py", line 76, in try_parse
    raise parse_error or Exception("unknown parse failure")
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/usort/util.py", line 65, in try_parse
    mod = cst.parse_module(
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/libcst/_parser/entrypoints.py", line 109, in parse_module
    result = _parse(
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/libcst/_parser/entrypoints.py", line 56, in _parse
    return _pure_python_parse(
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/libcst/_parser/entrypoints.py", line 89, in _pure_python_parse
    result = parser.parse()
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/libcst/_parser/base_parser.py", line 110, in parse
    self._add_token(token)
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/libcst/_parser/base_parser.py", line 186, in _add_token
    raise ParserSyntaxError(
libcst._exceptions.ParserSyntaxError: Syntax Error @ 2:1.
Incomplete input. Unexpectedly encountered end of file (EOF).

(
 ^
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/ufmt/__main__.py", line 4, in <module>
    main()
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/ufmt/cli.py", line 54, in check
    results = ufmt_paths(paths, dry_run=True)
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/ufmt/core.py", line 117, in ufmt_paths
    results = list(runner.run(all_paths, fn).values())
  File "/home/tim/code/wreck/.venv/lib/python3.9/site-packages/trailrunner/core.py", line 193, in run
    results = list(exe.map(func, paths))
  File "/usr/lib/python3.9/concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
libcst._exceptions.ParserSyntaxError: Syntax Error @ 2:1.
Incomplete input. Unexpectedly encountered end of file (EOF).

(
 ^
make: *** [Makefile:28: lint] Error 1
```

**Comment by jreese** [comment]
I believe this was fixed in 2.0a2.
